# === common ===
spring:
  config:
    import: classpath:application-common.yml
  main:
    web-application-type: none
  application:
    name: hangsha-batch
  profiles:
    default: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul