spring:
  main:
    web-application-type: none
  application:
    name: hangsha-batch

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/campus_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jackson:
    time-zone: Asia/Seoul