oci:
  storage:
    namespace: ax1dvc8vmenm
    region: ap-chuncheon-1
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/campus_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: password

oci:
  auth:
    type: config
  vault:
    secret-ids: "ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqawu5rdzjsnl3zot7ii3svbmup5akjqljppt4d5wwjimgq"
  storage:
    bucket: hangsha-asset-dev

logging:  # for local debugging
  level:
    org.springframework.boot.context.config: TRACE
    org.springframework.core.env: DEBUG
    com.oracle.bmc: DEBUG
    com.team1.hangsha: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url:
    username:
    password:

oci:
  vault:
    secret-ids: "ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqagobbswqnpk5ezitpkdb7kidfrnhuuotu5yudac62bhpa"
  storage:
    bucket: hangsha-asset-dev
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url:
    username:
    password:

oci:
  vault:
    secret-ids: "ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqaf77fsikezk5n2xakqhaokn33iedgj7wv6pxqa4q23aea"
  storage:
    bucket: hangsha-asset